spring:
  application:
    name: AIService
  data:
    mongodb:
      uri: mongodb://localhost:27017/AiRecommendations
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-process-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.AIService.model.Activity
        spring.json.trusted.packages: "*"
        spring.json.ignore.unknown: true
server:
  port: 8083


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


kafka:
  topic:
    name: activity-events


gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}


